version: '3.9'
services:
  app:
    image: docker-nextjs-dev
    build: .
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    ports:
      - '33000:3000'
    command: bash -c "npm run dev"

volumes:
  node_modules:
