import { Card } from '@/components/Card';
import { Description } from '@/components/Description';
import { Footer } from '@/components/Footer';
import { Title } from '@/components/Title';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '@/styles/Home.module.scss';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Title />
        <Description />

        <div className={styles.grid}>
          <Card
            link="https://nextjs.org/docs"
            heading="Documentation &rarr;"
            description="Find in-depth information about Next.js features and API."
          />

          <Card
            link="https://nextjs.org/learn"
            heading="Learn &rarr;"
            description="Learn about Next.js in an interactive course with quizzes!"
          />

          <Card
            link="https://github.com/vercel/next.js/tree/canary/examples"
            heading="Examples &rarr;"
            description="Discover and deploy boilerplate example Next.js projects."
          />

          <Card
            link="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            heading="Deploy &rarr;"
            description="Instantly deploy your Next.js site to a public URL with Vercel."
          />
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Home;
